apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-lab-postgres-shared-data
  namespace: devops-lab-app-prod-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
