apiVersion: v1
kind: Service
metadata:
  name: devops-lab-postgres-shared
  namespace: devops-lab-app-prod-data
spec:
  selector:
    app.kubernetes.io/name: devops-lab-postgres-shared
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
